### ISSUE TITLE
tn in state validated cannot be purged

### ISSUE THREAD

**Issue by bjoern-r** [6G-SANDBOX/TNLCM#67]
# Prerequisites

- [x] I am running the latest version.
- [x] I have checked if there is already an issue created with the same characteristics.

# Expected Behavior

TN purged vom tnlcm

# Current Behavior

the TNLCM returns error 500

```jaml
{
  "message": "'NoneType' object has no attribute 'split'"
}
```

# Bug Information (if applicable)

## Steps to Reproduce

 - upload a new TN
 - try to purge the TN

## Context

- Browser: Firefox, Chrome, Safari, Microsoft Edge, Opera, etc.
- Browser Version: ---
- Operating System: linux

**Comment by CarlosAndreo** [comment]
Fixed!
